# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

sphinx:
   configuration: module_4/source/conf.py

python:
   install:
   - requirements: module_4/requirements.txt  # Add module_4/ path
   - method: pip
     path: module_4  # Also add this path

formats:
  - htmlzip